import type { MenuProps } from './interfaces/menu'

export const LIST_MENU = <MenuProps[]>[
  {
    name: 'Beranda',
    href: '/admin',
    icon: 'home',
    status: true,
    order: 1,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Otoritasi',
    href: '/admin/auth',
    icon: 'shield-check',
    status: true,
    order: 2,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'Pengguna',
        href: '/admin/auth/users',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Hak Akses',
        href: '/admin/auth/role-privilages',
        icon: 'chevron-right',
        status: true,
        order: 2,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
  {
    name: 'System',
    href: '#',
    icon: 'command-line',
    status: true,
    order: 3,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'Golongan Darah',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Pendidikan Terakhir',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 2,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Suku',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 3,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Status Pernikahan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 4,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Marketing',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 5,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Agama',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 6,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Title',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 7,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Status Pekerjaan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 8,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Title',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 9,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Provinsi (Area)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 10,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Kota (Area)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 11,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Kecamatan (Area)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 12,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Kelurahan (Area)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 13,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
  {
    name: 'Tambahan',
    href: '#',
    icon: 'puzzle-piece',
    status: true,
    order: 4,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'Obat-Obatan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Layanan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 2,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Asuransi & Jaminan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 3,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Penyakit (Subjective)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 4,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Diagnosa (Assesment)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 5,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Prognosa (Assesment)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 6,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'ICD-10 (Assesment)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 7,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
  {
    name: 'Info Klinik',
    href: '/admin/clinic-info',
    icon: 'presentation-chart-bar',
    status: true,
    order: 5,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Jadwal Praktik',
    href: '#',
    icon: 'calendar-days',
    status: true,
    order: 6,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Kontak (Pasien)',
    href: '#',
    icon: 'users',
    status: true,
    order: 7,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Rawat Jalan',
    href: '#',
    icon: 'beaker',
    status: true,
    order: 8,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'Penilaian (Assesment)',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
      {
        name: 'Asuransi & Jaminan',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 2,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
  {
    name: 'Rekam Medis',
    href: '#',
    icon: 'book-open',
    status: true,
    order: 9,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Inventori',
    href: '#',
    icon: 'squares-2x2',
    status: true,
    order: 10,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Pembelian',
    href: '#',
    icon: 'calculator',
    status: true,
    order: 11,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'lah gitu',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
  {
    name: 'Laporan',
    href: '#',
    icon: 'chart-bar',
    status: true,
    order: 12,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [],
  },
  {
    name: 'Statistik (CRM)',
    href: '#',
    icon: 'variable',
    status: true,
    order: 13,
    privilage: {
      create: true,
      read: true,
      update: true,
      delete: true,
      import: true,
      export: true,
    },
    children: [
      {
        name: 'lah gitu',
        href: '#',
        icon: 'chevron-right',
        status: true,
        order: 1,
        privilage: {
          create: true,
          read: true,
          update: true,
          delete: true,
          import: true,
          export: true,
        },
      },
    ],
  },
]
